# Generated by Django 4.0.6 on 2022-12-08 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('link_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_url', models.TextField(max_length=255)),
                ('cut_url', models.TextField(max_length=30)),
            ],
            options={
                'db_table': 'links',
                'managed': False,
            },
        ),
    ]
